# Generated by Django 2.2.16 on 2020-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='notice.Tag'),
        ),
    ]
