# Generated by Django 2.2.16 on 2020-09-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taglistrelatedboard',
            unique_together={('notice', 'tag')},
        ),
    ]
