# Generated by Django 2.2.16 on 2020-09-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20200923_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='tag',
            field=models.ManyToManyField(related_name='board', to='notice.Tag'),
        ),
    ]
