# Generated by Django 2.2.16 on 2020-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20200923_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=100),
        ),
    ]
