# Generated by Django 2.2.16 on 2020-09-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200923_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='tag_set',
            new_name='tag',
        ),
    ]
