# Generated by Django 2.2.16 on 2020-09-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date_created')),
                ('modified', models.DateTimeField(verbose_name='date_modified')),
            ],
        ),
    ]
