# Generated by Django 2.2.16 on 2020-09-15 08:46

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200915_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
    ]
