# Generated by Django 2.2.16 on 2020-09-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200916_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='status',
        ),
    ]
