# Generated by Django 2.2.16 on 2020-09-16 05:31

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_board_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
