# Generated by Django 2.2.16 on 2020-09-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
