# Generated by Django 2.2.16 on 2020-09-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_history_modifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='modifiedDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
    ]
