# Generated by Django 2.2.16 on 2020-09-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20200917_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='modifiedDate',
            new_name='board',
        ),
        migrations.RemoveField(
            model_name='history',
            name='currentUser',
        ),
        migrations.AlterField(
            model_name='history',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='board.Board'),
        ),
    ]
