# Generated by Django 2.2.16 on 2020-10-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0054_auto_20201004_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='board.Board'),
        ),
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(related_name='board', to='board.Tag'),
        ),
    ]
