# Generated by Django 2.2.16 on 2020-10-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0055_auto_20201005_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='board', to='board.Tag'),
        ),
        migrations.AlterField(
            model_name='history',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='board.Board'),
        ),
    ]
