# Generated by Django 2.2.16 on 2020-10-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0057_auto_20201005_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='history',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='board.Board'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
