# Generated by Django 2.2.16 on 2020-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionboard',
            old_name='contents',
            new_name='content',
        ),
        migrations.AddField(
            model_name='answerboard',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
